services:
  strapi:
    container_name: strapi
    image: darkshrine/bostongrad-strapi:latest
    restart: always
    env_file: .env
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: ./data/data.db
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - data:/opt/app/data
      - public:/opt/app/public
      - config_sync:/opt/app/config/sync
    ports:
      - "1337:1337"
    networks:
      - my-network

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - .env
    networks:
      - my-network

volumes:
  data:
  public:
  config_sync:

networks:
  my-network:
    name: my-network
    driver: bridge
